### ISSUE TITLE
error when build system

### ISSUE THREAD

**Issue by m7a10a3** [omarrx024/lux#1]
# when I run the command `make`,  showing this error.
`make`
> 2 warnings generated.
> ld -melf_i386 -nostdlib -nodefaultlibs -O2 -T kernel/ld_i386.ld *.o *.a -o iso/boot/kernel.sys
> syscall.o: In function `syscall_init':
> kernel/tasking/syscall.c:(.text+0x1): undefined reference to `syscall_handler'
> Makefile:10: recipe for target 'lux32' failed
> make: *** [lux32] Error 1
>
## screenshot
![2018-03-30-102226_1280x800_scrot](https://user-images.githubusercontent.com/33102737/38130718-6a0d0ad4-3404-11e8-9650-2776d3764bcf.png)

**Comment by omarrx024** [comment]
Running just `make` builds the 32-bit version of lux, and currently system calls have only been implemented for x86_64 for testing. Most of my focus is on the 64-bit version, but the 32-bit version will catch up. This difference has to be there because assembly is not portable, and stuff like interrupt handler stubs and the syscall handler have to be written in assembly. 

Try `make lux64` and it will build.

**Comment by m7a10a3** [comment]
### OK, good luck 👍
